cask_args appdir: "/Applications"

brew "docker-completion"
brew "bat"
brew "coreutils"
brew "eza"
brew "ghq"
brew "git"
brew "go"
brew "mas"
brew "nano"
brew "rsync"
brew "source-highlight"
brew "starship"
brew "wget"

cask "1password@7"
cask "alfred"
cask "bettertouchtool"
cask "daisydisk"
cask "dash"
cask "docker-desktop"
cask "dropbox"
cask "font-fira-code-nerd-font"
cask "fork"
cask "fuwari"
cask "google-chrome"
cask "iterm2"
cask "karabiner-elements"
cask "keka"
# cask "omnigraffle"
cask "path-finder"
cask "readdle-spark"
cask "tableplus"
cask "visual-studio-code"
cask "xnconvert"

mas "AdGuard for Safari", id: 1440147259
mas "uBlacklist for Safari", id: 1547912640
