# tap "heroku/brew"
# tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
# tap "homebrew/core"
# tap "waltarix/customs"

# brew "libyaml"
# brew "ansible"
# brew "autoconf"
# brew "automake"
brew "bat"
# brew "icu4c"
# brew "fontconfig"
# brew "gettext"
# brew "libffi"
brew "coreutils"
# brew "direnv"
brew "exa"
# brew "libtool"
# brew "lame"
# brew "libsodium"
# brew "ffmpeg"
# brew "fontforge"
# brew "ghq"
brew "git"
# brew "go"
# brew "highlight"
# brew "hugo"
# brew "imageoptim-cli"
# brew "mackup"
# brew "ncurses"
# brew "nano"
# brew "oniguruma"
# brew "peco"
# brew "rsync"
# brew "selenium-server-standalone"
# brew "source-highlight"
# brew "tig"
brew "wget"

cask "1password"
cask "alfred"
# cask "bettertouchtool"
# cask "chromedriver"
cask "daisydisk"
cask "dash"
# cask "docker"
cask "flux"
cask "font-inconsolata-nerd-font"
cask "font-myrica"
# cask "font-myricam"
# cask "fork"
cask "fuwari"
# cask "gas-mask"
cask "google-chrome"
cask "google-japanese-ime"
cask "hyperswitch"
# cask "imageoptim"
cask "iterm2"
cask "karabiner-elements"
# cask "omnifocus"
# cask "omnigraffle"
cask "path-finder"
# cask "qlcolorcode"
# cask "qlmarkdown"
# cask "qlstephen"
# cask "quicklook-json"
cask "visual-studio-code"
# cask "vmware-fusion"
