[settings]
experimental = true
disable_backends = ["asdf", "vfox"]

[tools]
"aqua:peteretelej/tree" = "latest"
"aqua:rossmacarthur/sheldon" = "latest"
bat = "latest"
deno = "2.7"
eza = "latest"
fd = "latest"
gallery-dl = "latest"
go = "1.26"
node = "24"
python = "3.14"
ripgrep = "latest"
rust = "latest"
