[settings]
experimental = true
disable_backends = ["asdf", "vfox"]

[tools]
"aqua:rossmacarthur/sheldon" = "latest"
deno = "2.7"
gallery-dl = "latest"
go = "1.26"
node = "24"
python = "3.14"
rust = "latest"
