[[input.prepend_keymap]]
on   = "<Esc>"
run  = "close"
desc = "Cancel input"

[mgr]
prepend_keymap = [
  { on = [ "c", "h" ], run = "shell 'md5 -r \"$@\" | LESS=\"${LESS/-F /}\" less' --block", desc = "md5 of selected" },
  { on = "T", run = "plugin toggle-pane max-preview", desc = "Maximize or restore the preview pane" },
  # { on = "P", run = "plugin toggle-pane min-preview", desc = "Hide or restore the preview pane" },

  { on = ["c", "r"], run = "plugin revert-webm", desc = "revert_rename_webm" },
  { on = "<Enter>", run = "plugin smart-enter", desc = "Enter the child directory, or open the file" },

  { on = [ "m", "a" ], run = "linemode size_mtime",      desc = "Linemode: size + mtime (compact)" },
  { on = [ "m", "A" ], run = "linemode size_mtime_long", desc = "Linemode: size + mtime (long)" },
  # Sorting does not override linemode
  { on = [ ",", "m" ], run = [ "sort mtime --reverse=no" ], desc = "Sort by modified time" },
  { on = [ ",", "M" ], run = [ "sort mtime --reverse=yes" ], desc = "Sort by modified time (reverse)" },
  { on = [ ",", "b" ], run = [ "sort btime --reverse=no" ], desc = "Sort by birth time" },
  { on = [ ",", "B" ], run = [ "sort btime --reverse=yes" ], desc = "Sort by birth time (reverse)" },
  { on = [ ",", "s" ], run = [ "sort size --reverse=no" ], desc = "Sort by size" },
  { on = [ ",", "S" ], run = [ "sort size --reverse=yes" ], desc = "Sort by size (reverse)" },
]
