[mgr]
sort_by = "natural"
linemode = "size_and_mtime"

[flavor]
dark = "catppuccin-mocha"

[plugin]
prepend_fetchers = [
  { url = "*", run = "git", group = "git" },
  { url = "*/", run = "git", group = "git" },
]

[preview]
max_width = 10000
max_height = 10000
image_quality = 85 # Bump from default 75 to 85-90 for sharper retina rendering

[opener]
qlpreview = [
  { run = 'qlmanage -p %s', desc = "Quick Look Preview"}
]

[open]
prepend_rules = [
  { mime = "image/*", use = ["qlpreview", "open", "reveal"] },
]
