[mgr]
sort_by = "natural"

[flavor]
dark = "catppuccin-mocha"

[preview]
max_width = 3840
max_height = 2160
image_quality = 85 # Bump from default 75 to 85-90 for sharper retina rendering

[opener]
qlpreview = [
  { run = 'qlmanage -p %s', desc = "Quick Look Preview"}
]

[open]
prepend_rules = [
  { mime = "image/*", use = ["qlpreview", "open", "reveal"] },
]
